# Generated by Django 3.1.2 on 2021-02-21 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderPlaced',
            new_name='OrderPlaced',
        ),
    ]
