# Generated by Django 3.1.2 on 2021-02-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210221_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='disctrict',
            new_name='district',
        ),
    ]
